#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.10.5

before_install:
  - export DJANGO_SETTINGS_MODULE=avalanche.settings
  - export PYTHONPATH=$HOME/builds/NtwariJoshua/Avalanche
  - export TRAVIS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py makemigrations tenants
  - python manage.py migrate_schemas --shared

script:
  - python manage.py test