# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_operations', '0002_auto_20170214_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=7)),
            ],
        ),
    ]
