# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_operations', '0003_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='passenger_seats',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
