# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_token',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
